name: ğŸ“ Draft Release Notes

on:
  workflow_run:
    workflows: ["ğŸ”¼ Bump Version"]
    types: [completed]

permissions:
  contents: write
  pull-requests: write

jobs:
  update_release_draft:
    if: github.repository == 'brkcvlk/MLFCrafter'
    runs-on: ubuntu-latest

    steps:
      - uses: release-drafter/release-drafter@v6.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        